platform :ios, '9.0'

target 'RedSolApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
	pod 'Firebase'

  # Pods for RedSolApp

end
