# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RedSolApp-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RedSolApp-iOS

  target 'RedSolApp-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RedSolApp-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
