platform :ios, '9.0'

target 'RedSolApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
   use_modular_headers!
  # Pods for RedSolApp

   pod 'Apollo'


  target 'RedSolApp-Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RedSolApp-UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
