on: pull_request
name: iOS Build
jobs:
  test:
    name: Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.5,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build on ${destination}
        run: |
          xcodebuild clean build -project RedSolApp.xcodeproj -scheme RedSolApp -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          bash <(curl -s https://codecov.io/bash)
        env: 
         destination: ${{ matrix.destination }}